buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.2'
    }
}

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.android.libraries.mapsplatform.secrets-gradle-plugin'
    id 'com.google.gms.google-services'
}

// Carica secrets.properties per ottenere la chiave
def secretsPropertiesFile = rootProject.file("secrets.properties")
def secretsProperties = new Properties()
secretsProperties.load(new FileInputStream(secretsPropertiesFile))

android {
    namespace 'it.uninsubria.catchstars'
    compileSdkVersion 34

    defaultConfig {
        applicationId "it.uninsubria.catchstars"
        minSdkVersion 23
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        // Passa la chiave direttamente da secrets.properties al Manifest
        manifestPlaceholders = [
                API_KEY_MAPS: "${secretsProperties['API_KEY_MAPS']}"
        ]
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    // Aggiungi la chiave API a BuildConfig per usarla nel codice, se necessario
    buildTypes.each {
        it.buildConfigField 'String', 'API_KEY_MAPS', "\"${secretsProperties['MAPS_API_KEY']}\""
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.gms:play-services-maps:19.0.0'
    implementation 'androidx.annotation:annotation:1.8.2'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.8.6'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.6'
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'com.google.firebase:firebase-auth-ktx:23.0.0'
    implementation 'com.google.firebase:firebase-database-ktx:21.0.0'
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'com.google.firebase:firebase-crashlytics-buildtools:3.0.2'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

    //dipendenza firebase
    implementation platform('com.google.firebase:firebase-bom:32.1.0')
    implementation 'com.google.firebase:firebase-auth-ktx'
    implementation 'com.google.firebase:firebase-core:21.1.1'
    implementation "com.google.firebase:firebase-database:21.0.0"

    //dipendenze google maps
    implementation 'com.google.android.gms:play-services-maps:19.0.0'
    implementation 'com.google.android.gms:play-services-location:21.3.0'

    //dipendenza SQLite
    implementation "androidx.sqlite:sqlite:2.4.0"
}

